title: "FirebaseとFlutterで通知機能を実装してみたんじゃ"
summary: "FirebaseとFlutterで通知機能を実装してみたんじゃ"
topics: ["Flutter","Firebase","FCM"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - intoro
  - install
  - xcode_setting
  - firebase_setting
  - dart_setting
  - notice_test
