title: "FirebaseとFlutterで通知機能を実装してみたんじゃ"
summary: "FirebaseとFlutterで通知機能を実装してみたんじゃ"
cover_image: "/images/next_flutter_notice/cover.png"
topics: ["Flutter","Firebase","FCM"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
publication_name: "genai"
chapters:
  - intoro
  - install
  - xcode_setting
  - firebase_setting
  - dart_setting
  - notice_test
